from typing import List, TypedDict


# --- Filter Lists ---
BLACKLIST_DOMAINS = [
    # Known spam / low-quality sources
    "ts2.tech",
    "biztoc.com",
    "bignewsnetwork.com",
    "fagenwasanni.com",
    "crypto.news",
    "investing.com",
    # Paywalled — scraping fails consistently
    "forbes.com",
    "bloomberg.com",
    "ft.com",
    # Technical scraping failures
    "eetasia.com",
    # Non-article content (video, social media)
    "youtube.com",
    "instagram.com",
    # Crypto / finance noise
    "coinmarketcap.com",
    "mexc.com",
    "aastocks.com",
]


# --- Target Companies ---
class TargetCompany(TypedDict):
    name: str
    keywords: List[str]


TARGET_COMPANIES: List[TargetCompany] = [
    {
        "name": "OpenAI",
        "keywords": [
            "openai",
            "chatgpt",
            "gpt-",
            "sam altman",
            "codex",
            "sora",
            "mark chen",
        ],
    },
    {
        "name": "Google DeepMind",
        "keywords": [
            "deepmind",
            "gemini",
            "google ai",
            "google",
            "demis hassabis",
            "veo",
            "ai studio",
            "antigravity",
            "nano banana",
            "gemma",
            "imagen",
            "synthid",
            "lyria",
            "alphago",
            "alphazero",
        ],
    },
    {
        "name": "Microsoft AI",
        "keywords": [
            "microsoft",
            "copilot",
            "satya nadella",
            "azure ai",
            "phi",
            "foundry",
            "aurora",
            "magma",
            "muse",
            "autogen",
        ],
    },
    {
        "name": "Anthropic",
        "keywords": [
            "anthropic",
            "claude",
            "dario amodei",
            "opus",
            "sonnet",
            "haiku",
        ],
    },
    {
        "name": "NVIDIA",
        "keywords": [
            "nvidia",
            "jensen huang",
            "gpu",
            "blackwell",
            "omniverse",
            "dgx",
            "hgx",
            "igx",
            "ovx",
            "geforce",
            "nemo",
            "nim",
            "dynamo",
            "metropolis",
            "cosmos",
            "isaac groot",
            "clara",
            "nemotron",
        ],
    },
    {
        "name": "Meta AI",
        "keywords": [
            "meta ai",
            "llama",
            "mark zuckerberg",
            "facebook ai",
            "sam",
            "dino",
            "meta segment",
            "meta",
            "v-jepa",
            "llama",
        ],
    },
    {"name": "xAI", "keywords": ["xai", "grok", "elon musk", "colossus"]},
    {
        "name": "Apple",
        "keywords": [
            "apple intelligence",
            "siri",
            "tim cook",
            "apple ai",
            "apple",
            "amar subramanya",
        ],
    },
    {
        "name": "DeepSeek",
        "keywords": [
            "deepseek",
            "deepseek-v3",
            "deepseek-coder",
            "deepseek-r1",
            "deepseekmoe",
            "liang wengfeng",
            "wengfeng liang",
            "high-flyer",
        ],
    },
    {
        "name": "Mistral AI",
        "keywords": [
            "mistral",
            "mistral large",
            "mistral medium",
            "mistral family",
            "mistral small",
            "nemo",
            "ministral",
            "voxtral",
            "document ai",
            "le chat",
            "arthur mensch",
            "guillaume lample",
            "timothee lacroix",
            "mixtral",
            "codestral",
            "magistral",
        ],
    },
    {
        "name": "Perplexity",
        "keywords": [
            "perplexity",
            "aravind srinivas",
            "denis yarats",
            "johnny ho",
            "andy konwinski",
            "perplexity sonar",
            "sonar-pro",
            "comet",
            "pplx-api",
        ],
    },
    {
        "name": "Black Forest Labs",
        "keywords": [
            "black forest labs",
            "flux.1",
            "flux model",
            "flux.2",
            "flux",
            "robin rombach",
            "andreas blattmann",
            "axel sauer",
            "patrick esser",
            "image generation",
        ],
    },
    {
        "name": "LangChain",
        "keywords": [
            "langchain",
            "langgraph",
            "langsmith",
            "harrison chase",
            "llm orchestration",
            "ai agents",
            "ankush gola",
            "jacob lee",
            "deep agents",
        ],
    },
    {
        "name": "Helsing",
        "keywords": [
            "helsing",
            "defense ai",
            "torsten reil",
            "gundbert scherf",
            "niklas köhler",
            "daniel ek",
            "software-defined defence",
            "hx-2",
            "hf-1",
            "sg-1",
            "fathom",
            "ca-1",
            "cirra",
            "centaur",
            "lura",
            "altra",
        ],
    },
    {
        "name": "Celonis",
        "keywords": [
            "celonis",
            "alex rinke",
            "bastian nominacher",
            "martin klenk",
            "process mining",
            "execution management",
            "process intelligence",
            "enterprise ai",
        ],
    },
    {
        "name": "DeepL",
        "keywords": [
            "deepl",
            "jarek kutylowski",
            "ai translation",
            "deepl write",
            "deepl agent",
            "neural machine translation",
        ],
    },
    {
        "name": "Aleph Alpha",
        "keywords": [
            "aleph alpha",
            "jonas andrulis",
            "reto spörri",
            "samuel weinbach",
            "luminous",
            "pharia",
            "dora",
            "govtech",
            "sovereign ai",
            "industrial llm",
            "heidelberg ai",
        ],
    },
    {
        "name": "Oracle",
        "keywords": [
            "oracle",
            "larry ellison",
            "oci",
            "cohere",
            "heatwave",
            "oracle database 23ai",
            "safra catz",
            "ai vector search",
        ],
    },
]
